### ISSUE TITLE
api详情

### ISSUE THREAD

**Issue by Conanke888** [mizhexiaoxiao/vue-fastapi-admin#14]
您好 能不能增加一个数据模型，比如我想查看某个 api 具体的参数、数据格式、返回值等等

**Comment by mizhexiaoxiao** [comment]
api具体参数和数据格式在schemas都有定义，返回值虽然没有定义，但有to_dict方法，一般都是所有字段。
没太明白这个数据模型是什么，orm model？用来做什么？
