### ISSUE TITLE
conda+windows环境下运行不了

### ISSUE THREAD

**Issue by RyanCCC** [mizhexiaoxiao/vue-fastapi-admin#19]
博主你好，请问如何在windows下用conda运行项目的api？谢谢。

**Comment by cvtutorials** [comment]
同问，poetry安装麻烦

**Comment by cvtutorials** [comment]
可以手动安装pyproject.toml中的python包，然后在根目录下运行python run.py即可

**Comment by cvtutorials** [comment]
![image](https://github.com/mizhexiaoxiao/vue-fastapi-admin/assets/35392997/95cbb82f-bb65-4e81-aa7c-e5dcd1eb415a)
