### ISSUE TITLE
API请求阻塞问题

### ISSUE THREAD

**Issue by OtaviaW** [mizhexiaoxiao/vue-fastapi-admin#28]
我在fork了这个项目之后成功运行了后端服务，但是访问 http://localhost:9999/docs 查看API文档时出现了请求阻塞，刷新页面都是处于pending状态。

**Comment by mizhexiaoxiao** [comment]
看下是什么请求阻塞？
如果是swagger静态资源，应该是CDN挂了，隔段时间再请求试试，或者下载js和css到本地进行挂载访问

**Comment by OtaviaW** [comment]
我今天测试之后发现是涉及到数据库读写方面的请求时我这都会出现请求堵塞
![image](https://github.com/mizhexiaoxiao/vue-fastapi-admin/assets/58646711/7656b394-b54f-46de-83fc-3d738143e47a)
![image](https://github.com/mizhexiaoxiao/vue-fastapi-admin/assets/58646711/727eccf7-37a4-4cf4-a16b-b17c4f3e36b8)

**Comment by mizhexiaoxiao** [comment]
请检查一下数据库连接
