### ISSUE TITLE
表格排序的问题

### ISSUE THREAD

**Issue by xiaozihanpk** [mizhexiaoxiao/vue-fastapi-admin#49]
请教一下用Naive UI 的 @update:sorter="handleSorterChange"为什么触发不了，谢谢

![屏幕截图 2024-09-18 002832](https://github.com/user-attachments/assets/9d65ea3e-b611-4d90-8cbf-afe1ea57e82e)

**Comment by mizhexiaoxiao** [comment]
CrudTable是封装后的组件，要在内层原UI组件n-data-table那里添加

**Comment by xiaozihanpk** [comment]
下一版能不能把这个加上去，感谢感谢

**Comment by xiaozihanpk** [comment]
![image](https://github.com/user-attachments/assets/5c29ba1d-0f6d-411a-8a2f-438bbc66c8d4)
还有这个重置按键，没有重置日期和下拉框。

**Comment by mizhexiaoxiao** [comment]
请求方法重置已修复。日期不重置，设计如此
