### ISSUE TITLE
你好，有数据库文件吗

### ISSUE THREAD

**Issue by dgo2dance** [mizhexiaoxiao/vue-fastapi-admin#5]
你好，有数据库文件吗

**Comment by mizhexiaoxiao** [comment]
你指的是什么数据库文件？数据库配置文件在app/settings/config.py

**Comment by dgo2dance** [comment]
能用mysql数据库吗   我以为是mysql数据库呢  指的数据库初始化脚本，建表语句与数据初始化

**Comment by mizhexiaoxiao** [comment]
> 能用mysql数据库吗 我以为是mysql数据库呢 指的数据库初始化脚本，建表语句与数据初始化

项目数据库操作使用[tortoise-orm](https://github.com/tortoise/tortoise-orm)，支持多种数据库 SQLite、PostgreSQL、MySQL、Microsoft SQL Server/Oracle，修改项目数据库配置即可。
项目启动就会自动建表，所以无需建表语句。同时项目内已经写好了启动时初始化数据的代码，创建超级管理员和系统菜单。

**Comment by dgo2dance** [comment]
好的   多谢多谢
